# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_twitteroutquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.CharField(max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='TwitterOutQuery',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='query',
            new_name='tokens',
        ),
    ]
